# Generated by Django 4.0.5 on 2022-09-22 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deceased',
            old_name='lot_id',
            new_name='lot',
        ),
    ]
