# Generated by Django 4.0.5 on 2022-09-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cemetery',
            name='latitude',
            field=models.CharField(default=2, max_length=64),
        ),
        migrations.AlterField(
            model_name='cemetery',
            name='longitude',
            field=models.CharField(default=1, max_length=64),
        ),
        migrations.AlterField(
            model_name='lot',
            name='latitude',
            field=models.CharField(default=2, max_length=64),
        ),
        migrations.AlterField(
            model_name='lot',
            name='longitude',
            field=models.CharField(default=1, max_length=64),
        ),
    ]
