# Generated by Django 4.0.5 on 2022-11-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmis', '0002_remove_cemetery_center'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='cemetery',
            options={'verbose_name_plural': 'cemeteries'},
        ),
        migrations.AlterModelOptions(
            name='deceased',
            options={'verbose_name_plural': 'deceased'},
        ),
        migrations.AlterModelOptions(
            name='grave',
            options={'verbose_name_plural': 'graves'},
        ),
        migrations.AlterModelOptions(
            name='lot',
            options={'verbose_name_plural': 'lots'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name_plural': 'sections'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'status'},
        ),
        migrations.AlterField(
            model_name='deceased',
            name='middle_name',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
