# Generated by Django 4.0.5 on 2022-10-21 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmis', '0002_rename_lot_id_deceased_lot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='cemetery',
            options={'verbose_name': 'cemetery', 'verbose_name_plural': 'cemeteries'},
        ),
        migrations.AlterModelOptions(
            name='deceased',
            options={'verbose_name': 'deceased', 'verbose_name_plural': 'deceased'},
        ),
        migrations.AlterModelOptions(
            name='lot',
            options={'verbose_name': 'lot', 'verbose_name_plural': 'lots'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'status', 'verbose_name_plural': 'status'},
        ),
    ]
