# Generated by Django 4.0.5 on 2022-10-31 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmis', '0006_rename_latitude_lot_geobl_rename_longitude_lot_geobr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'section',
                'verbose_name_plural': 'sections',
            },
        ),
        migrations.RenameField(
            model_name='lot',
            old_name='geobl',
            new_name='polygon',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='geobr',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='geotl',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='geotr',
        ),
        migrations.AddField(
            model_name='status',
            name='polygon',
            field=models.CharField(default=123123, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lot',
            name='sections',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmis.sections'),
        ),
    ]
