# Generated by Django 4.0.5 on 2022-10-31 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmis', '0007_sections_rename_geobl_lot_polygon_remove_lot_geobr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(default='test', max_length=32),
        ),
        migrations.AlterField(
            model_name='status',
            name='polygon',
            field=models.CharField(default='123', max_length=256),
        ),
        migrations.CreateModel(
            name='Grave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deceased', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmis.deceased')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmis.lot')),
            ],
            options={
                'verbose_name': 'grave',
                'verbose_name_plural': 'graves',
            },
        ),
    ]
