# Generated by Django 4.0.5 on 2022-10-31 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmis', '0008_alter_status_name_alter_status_polygon_grave'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sections',
            new_name='Section',
        ),
    ]
