# Generated by Django 4.0.5 on 2022-10-31 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmis', '0010_remove_status_polygon_section_polygon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='occupied_layer',
        ),
    ]
