# Generated by Django 4.0.5 on 2022-10-31 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmis', '0011_remove_lot_occupied_layer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deceased',
            name='lot',
        ),
    ]
