# Generated by Django 4.0.5 on 2022-10-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmis', '0012_remove_deceased_lot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='polygon',
            field=models.CharField(max_length=128),
        ),
    ]
